---
name: chatverse_chat_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  dynamic_theme: ^1.0.1
  shared_preferences: ^0.5.10
  flutter_spinkit: ^4.1.2+1
  page_transition: ^1.1.6
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1
  shimmer: ^1.1.1
  cached_network_image: ^2.3.1
  flutter_inner_drawer: ^0.5.7+2
  speech_to_text: ^2.6.0
  ntp: ^1.0.7
  fluttertoast: ^7.1.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+4
  firebase_messaging: ^7.0.0
  flutter_local_notifications: ^1.4.4+4
  video_player: ^0.10.12+5
  http: ^0.12.2
  lottie: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/
